name: "godot gut test"
on: push

jobs:
  execute-gut:
    name: Run GUT tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Anima Tests
        uses: ceceppa/godot-gut-ci@master
        with:
          godot_version: 4.1.2
          gut_params: -gdir=res://tests -gsuffix=.test.gd -gprefix=
